# Generated by Django 4.0.2 on 2022-03-17 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='bankaccount',
            field=models.CharField(blank='true', max_length=225, null='true'),
            preserve_default='true',
        ),
    ]
