# Generated by Django 4.0.2 on 2022-03-18 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0002_team_bankaccount'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='address1',
            field=models.CharField(blank='true', max_length=225, null='true'),
            preserve_default='true',
        ),
        migrations.AddField(
            model_name='team',
            name='address2',
            field=models.CharField(blank='true', max_length=225, null='true'),
            preserve_default='true',
        ),
        migrations.AddField(
            model_name='team',
            name='email',
            field=models.CharField(default=1, max_length=225),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='team',
            name='place',
            field=models.CharField(blank='true', max_length=225, null='true'),
            preserve_default='true',
        ),
        migrations.AddField(
            model_name='team',
            name='zipcode',
            field=models.CharField(blank='true', max_length=225, null='true'),
            preserve_default='true',
        ),
    ]
