# Generated by Django 4.0.2 on 2022-03-16 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0003_invoice_is_paid'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invoice',
            options={'ordering': ('-created_at',)},
        ),
        migrations.RenameField(
            model_name='item',
            old_name='Invoice',
            new_name='invoice',
        ),
    ]
