# Generated by Django 4.0.2 on 2022-03-17 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0004_alter_invoice_options_rename_invoice_item_invoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='bankaccount',
            field=models.CharField(blank='true', max_length=225, null='true'),
            preserve_default='true',
        ),
    ]
