# Generated by Django 4.0.2 on 2022-03-18 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0005_invoice_bankaccount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='sender_refer',
        ),
        migrations.AddField(
            model_name='invoice',
            name='sender_refer',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
