# Generated by Django 4.0.2 on 2022-03-19 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0006_remove_invoice_sender_reference_invoice_sender_refer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='bankaccount',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
    ]
